#!/usr/bin/env python3
"""
debug_detectors.py — fetch BTCUSDT spot data, run every detector,
and write one .pine file per detector for TradingView visual debugging.

Usage (from trading-copilot/ directory):
    python scripts/debug_detectors.py                          # all detectors
    python scripts/debug_detectors.py --tf 1h --bars 500      # custom TF/bars
    python scripts/debug_detectors.py --detector detect_fvg   # single detector
    python scripts/debug_detectors.py --list                   # show all names

Each output file can be pasted directly into TradingView:
    Pine Script Editor → New indicator → paste → Save → Add to chart
    (Switch chart to BTCUSDT and the matching timeframe first.)
"""

from __future__ import annotations

import argparse
import sys
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

# Ensure the project root is on the path when run directly
_HERE = Path(__file__).resolve().parent.parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

from copilot.data.base import VALID_TIMEFRAMES
from copilot.data.binance import BinanceSource, fetch_ohlcv_with_delta
from copilot.detectors.absorption_poi import check_absorption_at_poi
from copilot.detectors.bos import detect_bos
from copilot.detectors.breaker_block import detect_breaker_block
from copilot.detectors.cd_divergence_structure import check_cd_divergence_at_structure
from copilot.detectors.compression import detect_compression
from copilot.detectors.cumulative_delta import detect_cumulative_delta
from copilot.detectors.fib_zones import detect_fib_zones
from copilot.detectors.fractals import detect_fractals
from copilot.detectors.fvg import detect_fvg
from copilot.detectors.ifvg import detect_ifvg
from copilot.detectors.liquidity import detect_liquidity
from copilot.detectors.market_structure import detect_market_structure
from copilot.detectors.mitigation_block import detect_mitigation_block
from copilot.detectors.multi_tf import check_multi_tf_alignment
from copilot.detectors.order_block import detect_order_block
from copilot.detectors.rejection_block import detect_rejection_block
from copilot.detectors.sessions import current_killzone
from copilot.detectors.sponsored_candle import detect_sponsored_candle
from copilot.detectors.volume_profile import detect_volume_profile

# HTF to use for multi-TF alignment check, keyed by LTF
_HTF_MAP: dict[str, str] = {
    "1m": "15m", "3m": "1h", "5m": "1h",
    "15m": "4h", "30m": "4h", "1h": "4h", "4h": "1d", "1d": "1d",
}

# Canonical order — used for --list and validation
_ALL_DETECTOR_NAMES: list[str] = [
    "detect_fvg",
    "detect_order_block",
    "detect_ifvg",
    "detect_breaker_block",
    "detect_rejection_block",
    "detect_mitigation_block",
    "detect_liquidity",
    "detect_bos",
    "detect_volume_profile",
    "detect_market_structure",
    "detect_fractals",
    "detect_fib_zones",
    "detect_compression",
    "detect_sponsored_candle",
    "check_absorption_at_poi",
    "detect_cumulative_delta",
    "check_cd_divergence_at_structure",
    "current_killzone",
    "check_multi_tf_alignment",
]

# Detectors that need buy_vol/sell_vol/delta columns
_NEEDS_DELTA: frozenset[str] = frozenset({
    "detect_cumulative_delta",
    "check_cd_divergence_at_structure",
})

# Detectors that need a separate HTF OHLCV fetch
_NEEDS_HTF: frozenset[str] = frozenset({
    "check_multi_tf_alignment",
})

# Detectors that need ltf_ms_result (market-structure on LTF)
_NEEDS_MS: frozenset[str] = frozenset({
    "detect_fib_zones",
    "check_multi_tf_alignment",
})

# ── Pine Script helpers ───────────────────────────────────────────────────────

def _now_str() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _header(symbol: str, tf: str, indicator_name: str, future_bars: int) -> list[str]:
    return [
        f"// Generated by debug_detectors.py — {symbol} {tf} — {indicator_name} — {_now_str()}",
        "//@version=5",
        f'indicator("Debug: {indicator_name} | {symbol} {tf}", overlay=true, '
        "max_boxes_count=500, max_lines_count=500, max_labels_count=500)",
        "",
        "if barstate.islast",
    ]


def _ts_to_age(df: pd.DataFrame, ts_str: str) -> int:
    """Return how many bars ago *ts_str* occurred relative to the last bar."""
    try:
        ts = pd.Timestamp(ts_str)
        if ts.tzinfo is None:
            ts = ts.tz_localize("UTC")
        tf_sec = float((df.index[1] - df.index[0]).total_seconds())
        return max(1, int((df.index[-1] - ts).total_seconds() / tf_sec))
    except Exception:
        return 1


def _nothing(msg: str) -> list[str]:
    return [f'    label.new(bar_index, close, "{msg}", '
            f'style=label.style_label_left, color=color.gray, textcolor=color.white, size=size.small)']


def _assemble(header: list[str], body: list[str]) -> str:
    return "\n".join(header + body)


# ── Per-detector Pine Script body generators ─────────────────────────────────
# Each function returns a list[str] of indented Pine Script lines (4-space indent).
# They go inside the `if barstate.islast` block produced by _header().

def _pine_fvg(result: dict, future_bars: int) -> list[str]:
    lines = []
    for z in result.get("fvgs", []):
        age   = max(1, int(z["age_bars"]))
        top, bot = z["upper"], z["lower"]
        ztype = z["type"]
        state = z.get("fill_state", "untouched")
        bg = "color.new(color.teal, 80)" if ztype == "bullish" else "color.new(color.red, 80)"
        bc = "color.teal"               if ztype == "bullish" else "color.red"
        arrow = "U" if ztype == "bullish" else "D"
        lines.append(
            f'    box.new(bar_index-{age}, {top}, bar_index+{future_bars}, {bot}, '
            f'bgcolor={bg}, border_color={bc}, '
            f'text="FVG{arrow} {state}", text_size=size.tiny)'
        )
    return lines or _nothing("No FVGs detected")


def _pine_order_block(result: dict, future_bars: int) -> list[str]:
    lines = []
    for z in result.get("obs", []):
        age      = max(1, int(z["age_bars"]))
        top, bot = z["high"], z["low"]
        ztype    = z["type"]
        mit      = "mit" if z["is_mitigated"] else "active"
        fvgm     = "+FVG" if z["has_fvg_after"] else ""
        bg = "color.new(color.blue, 75)"   if ztype == "bullish" else "color.new(color.orange, 75)"
        bc = "color.blue"                  if ztype == "bullish" else "color.orange"
        arrow = "U" if ztype == "bullish" else "D"
        lines.append(
            f'    box.new(bar_index-{age}, {top}, bar_index+{future_bars}, {bot}, '
            f'bgcolor={bg}, border_color={bc}, '
            f'text="OB{arrow}{fvgm} {mit}", text_size=size.tiny)'
        )
    return lines or _nothing("No Order Blocks detected")


def _pine_ifvg(result: dict, future_bars: int) -> list[str]:
    lines = []
    for z in result.get("ifvgs", []):
        age      = max(1, int(z["age_bars"]))
        top, bot = z["upper"], z["lower"]
        ztype    = z["type"]
        tested   = "tested" if z["is_tested"] else "untested"
        bg = "color.new(color.lime, 70)"   if ztype == "bullish" else "color.new(color.maroon, 70)"
        bc = "color.lime"                  if ztype == "bullish" else "color.maroon"
        arrow = "U" if ztype == "bullish" else "D"
        lines.append(
            f'    box.new(bar_index-{age}, {top}, bar_index+{future_bars}, {bot}, '
            f'bgcolor={bg}, border_color={bc}, '
            f'text="IFVG{arrow} {tested}", text_size=size.tiny)'
        )
    return lines or _nothing("No IFVGs detected")


def _pine_breaker_block(result: dict, future_bars: int) -> list[str]:
    lines = []
    for z in result.get("breakers", []):
        age      = max(1, int(z["age_bars"]))
        top, bot = z["high"], z["low"]
        ztype    = z["type"]
        tested   = "tested" if z["is_tested"] else "untested"
        bg = "color.new(color.aqua, 70)"    if ztype == "bullish" else "color.new(color.fuchsia, 70)"
        bc = "color.aqua"                   if ztype == "bullish" else "color.fuchsia"
        arrow = "U" if ztype == "bullish" else "D"
        lines.append(
            f'    box.new(bar_index-{age}, {top}, bar_index+{future_bars}, {bot}, '
            f'bgcolor={bg}, border_color={bc}, '
            f'text="BRK{arrow} {tested}", text_size=size.tiny)'
        )
    return lines or _nothing("No Breaker Blocks detected")


def _pine_rejection_block(result: dict, future_bars: int) -> list[str]:
    lines = []
    for z in result.get("blocks", []):
        age      = max(1, int(z["age_bars"]))
        top, bot = z["high"], z["low"]
        ztype    = z["type"]
        mit      = "mit" if z["is_mitigated"] else "active"
        bg = "color.new(color.navy, 70)"   if ztype == "bullish" else "color.new(color.purple, 70)"
        bc = "color.navy"                  if ztype == "bullish" else "color.purple"
        arrow = "U" if ztype == "bullish" else "D"
        lines.append(
            f'    box.new(bar_index-{age}, {top}, bar_index+{future_bars}, {bot}, '
            f'bgcolor={bg}, border_color={bc}, '
            f'text="RejB{arrow} {mit}", text_size=size.tiny)'
        )
    return lines or _nothing("No Rejection Blocks detected")


def _pine_mitigation_block(result: dict, future_bars: int) -> list[str]:
    lines = []
    for z in result.get("blocks", []):
        age      = max(1, int(z["age_bars"]))
        top, bot = z["high"], z["low"]
        ztype    = z["type"]
        mit      = "mit" if z["is_mitigated"] else "active"
        bg = "color.new(color.green, 65)"  if ztype == "bullish" else "color.rgb(139, 0, 0, 65)"
        bc = "color.green"                 if ztype == "bullish" else "color.rgb(139, 0, 0, 0)"
        arrow = "U" if ztype == "bullish" else "D"
        lines.append(
            f'    box.new(bar_index-{age}, {top}, bar_index+{future_bars}, {bot}, '
            f'bgcolor={bg}, border_color={bc}, '
            f'text="MitB{arrow} {mit}", text_size=size.tiny)'
        )
    return lines or _nothing("No Mitigation Blocks detected")


def _pine_liquidity(result: dict, df: pd.DataFrame, future_bars: int) -> list[str]:
    lines = []
    for pool in result.get("buyside_liquidity", []):
        age   = max(1, int(pool["age_bars"]))
        price = pool["price"]
        ptype = pool["type"]
        touches = pool.get("touches", 0)
        lines += [
            f'    line.new(bar_index-{age}, {price}, bar_index+{future_bars}, {price}, '
            f'color=color.yellow, style=line.style_dashed, width=2)',
            f'    label.new(bar_index-{age}, {price}, "BSL {price} ({ptype}) x{touches}", '
            f'color=color.yellow, textcolor=color.black, style=label.style_label_right, size=size.tiny)',
        ]
    for pool in result.get("sellside_liquidity", []):
        age   = max(1, int(pool["age_bars"]))
        price = pool["price"]
        ptype = pool["type"]
        touches = pool.get("touches", 0)
        lines += [
            f'    line.new(bar_index-{age}, {price}, bar_index+{future_bars}, {price}, '
            f'color=color.purple, style=line.style_dashed, width=2)',
            f'    label.new(bar_index-{age}, {price}, "SSL {price} ({ptype}) x{touches}", '
            f'color=color.purple, textcolor=color.white, style=label.style_label_right, size=size.tiny)',
        ]
    for sweep in result.get("recent_sweeps", []):
        age   = _ts_to_age(df, sweep["sweep_ts"])
        level = sweep["swept_level"]
        side  = sweep["side"]
        closed = sweep.get("closed_back", False)
        color = "color.yellow" if side == "buyside" else "color.purple"
        style = "label.style_triangleup" if side == "sellside" else "label.style_triangledown"
        txt   = f"SW {side[:3]} {'cb' if closed else ''}"
        lines.append(
            f'    label.new(bar_index-{age}, {level}, "{txt}", '
            f'color={color}, textcolor=color.black, style={style}, size=size.small)'
        )
    return lines or _nothing("No liquidity levels detected")


def _pine_bos(result: dict, df: pd.DataFrame, future_bars: int) -> list[str]:
    bos_type = result.get("type", "none")
    if bos_type in (None, "none"):
        return _nothing("No BOS / MSS detected")
    bos_dir   = result.get("direction", "")
    level     = result.get("broken_level")
    break_ts  = result.get("break_ts")
    if not level:
        return _nothing(f"BOS type={bos_type} but no level")
    age   = _ts_to_age(df, break_ts) if break_ts else 2
    bc    = "color.green" if bos_dir == "bullish" else "color.red"
    disp  = result.get("displacement_candles", 0)
    atr_m = result.get("displacement_atr_multiple", 0)
    return [
        f'    line.new(bar_index-{age}, {level}, bar_index+{future_bars}, {level}, '
        f'color={bc}, style=line.style_solid, width=2)',
        f'    label.new(bar_index, {level}, "{bos_type} {bos_dir} | disp: {disp}b / {atr_m}xATR", '
        f'color={bc}, textcolor=color.white, style=label.style_label_left, size=size.small)',
    ]


def _pine_volume_profile(result: dict, bars: int, future_bars: int) -> list[str]:
    if result.get("status"):
        return _nothing(f"Volume profile: {result['status']}")
    lines = []
    poc = result.get("poc")
    vah = result.get("vah")
    val = result.get("val")
    loc = result.get("current_price_location", "")
    left = bars - 1
    if poc:
        lines += [
            f'    line.new(bar_index-{left}, {poc}, bar_index+{future_bars}, {poc}, '
            f'color=color.yellow, style=line.style_solid, width=2)',
            f'    label.new(bar_index, {poc}, "POC {poc} | {loc}", '
            f'color=color.yellow, textcolor=color.black, style=label.style_label_left, size=size.small)',
        ]
    if vah:
        lines += [
            f'    line.new(bar_index-{left}, {vah}, bar_index+{future_bars}, {vah}, '
            f'color=color.new(color.blue, 30), style=line.style_dotted, width=1)',
            f'    label.new(bar_index, {vah}, "VAH {vah}", '
            f'color=color.new(color.blue, 30), textcolor=color.white, style=label.style_label_left, size=size.tiny)',
        ]
    if val:
        lines += [
            f'    line.new(bar_index-{left}, {val}, bar_index+{future_bars}, {val}, '
            f'color=color.new(color.blue, 30), style=line.style_dotted, width=1)',
            f'    label.new(bar_index, {val}, "VAL {val}", '
            f'color=color.new(color.blue, 30), textcolor=color.white, style=label.style_label_left, size=size.tiny)',
        ]
    for node in result.get("hvn_nodes", [])[:15]:
        ph, pl = node["price_high"], node["price_low"]
        vpct   = node["volume_pct"]
        lines.append(
            f'    box.new(bar_index-{left}, {ph}, bar_index+{future_bars}, {pl}, '
            f'bgcolor=color.new(color.green, 88), border_color=color.new(color.green, 55), '
            f'text="HVN {vpct:.1f}%", text_size=size.tiny)'
        )
    for node in result.get("lvn_nodes", [])[:15]:
        ph, pl = node["price_high"], node["price_low"]
        vpct   = node["volume_pct"]
        lines.append(
            f'    box.new(bar_index-{left}, {ph}, bar_index+{future_bars}, {pl}, '
            f'bgcolor=color.new(color.red, 92), border_color=color.new(color.red, 65), '
            f'text="LVN {vpct:.1f}%", text_size=size.tiny)'
        )
    return lines or _nothing("Volume profile: no levels")


def _pine_market_structure(result: dict, df: pd.DataFrame, future_bars: int) -> list[str]:
    if result.get("status"):
        return _nothing(f"Market structure: {result['status']}")
    lines = []
    state         = result.get("state", "unknown")
    bars_in_state = result.get("bars_in_state", 0)
    current_price = result.get("current_price", 0)
    atr           = result.get("atr_14", 0)
    sh = result.get("last_swing_high", {})
    sl = result.get("last_swing_low", {})
    state_color = "color.green" if state == "bullish" else ("color.red" if state == "bearish" else "color.gray")
    if sh.get("price") and sh.get("ts"):
        age = _ts_to_age(df, sh["ts"])
        lines += [
            f'    line.new(bar_index-{age}, {sh["price"]}, bar_index+{future_bars}, {sh["price"]}, '
            f'color=color.red, style=line.style_dotted, width=1)',
            f'    label.new(bar_index-{age}, {sh["price"]}, "SwH {sh["price"]} ({sh.get("strength","")})", '
            f'color=color.red, textcolor=color.white, style=label.style_label_right, size=size.tiny)',
        ]
    if sl.get("price") and sl.get("ts"):
        age = _ts_to_age(df, sl["ts"])
        lines += [
            f'    line.new(bar_index-{age}, {sl["price"]}, bar_index+{future_bars}, {sl["price"]}, '
            f'color=color.green, style=line.style_dotted, width=1)',
            f'    label.new(bar_index-{age}, {sl["price"]}, "SwL {sl["price"]} ({sl.get("strength","")})", '
            f'color=color.green, textcolor=color.white, style=label.style_label_right, size=size.tiny)',
        ]
    lines.append(
        f'    label.new(bar_index, {current_price}, '
        f'"MS: {state} | {bars_in_state} bars | ATR: {atr}", '
        f'color={state_color}, textcolor=color.white, style=label.style_label_left, size=size.small)'
    )
    return lines


def _pine_fractals(result: dict, future_bars: int) -> list[str]:
    lines = []
    for f in result.get("fractals", []):
        age   = max(1, int(f["age_bars"]))
        price = f["price"]
        ftype = f["type"]
        swept = f["is_swept"]
        if ftype == "swing_high":
            style = "label.style_triangledown"
            color = "color.new(color.red, 50)"   if swept else "color.new(color.red, 0)"
            txt   = f"H {price}"
        else:
            style = "label.style_triangleup"
            color = "color.new(color.green, 50)" if swept else "color.new(color.green, 0)"
            txt   = f"L {price}"
        lines.append(
            f'    label.new(bar_index-{age}, {price}, "{txt}", '
            f'color={color}, textcolor=color.white, style={style}, size=size.tiny)'
        )
    return lines or _nothing("No fractals detected")


def _pine_fib_zones(result: dict, bars: int, future_bars: int) -> list[str]:
    if result.get("status"):
        return _nothing(f"Fib zones: {result['status']}")
    lines = []
    left = bars - 1
    pz   = result.get("premium_zone", {})
    dz   = result.get("discount_zone", {})
    ote  = result.get("ote", {})
    eq   = result.get("equilibrium")
    key  = result.get("key_levels", {})
    loc  = result.get("current_price_location", "")
    in_ote = result.get("in_ote", False)
    cur  = result.get("current_price", 0)
    fib_ratio = result.get("current_fib_ratio", 0)
    if pz.get("upper") and pz.get("lower"):
        lines.append(
            f'    box.new(bar_index-{left}, {pz["upper"]}, bar_index+{future_bars}, {pz["lower"]}, '
            f'bgcolor=color.new(color.red, 90), border_color=color.new(color.red, 50), '
            f'text="Premium", text_size=size.small)'
        )
    if dz.get("upper") and dz.get("lower"):
        lines.append(
            f'    box.new(bar_index-{left}, {dz["upper"]}, bar_index+{future_bars}, {dz["lower"]}, '
            f'bgcolor=color.new(color.green, 90), border_color=color.new(color.green, 50), '
            f'text="Discount", text_size=size.small)'
        )
    if ote.get("upper") and ote.get("lower"):
        lines.append(
            f'    box.new(bar_index-{left}, {ote["upper"]}, bar_index+{future_bars}, {ote["lower"]}, '
            f'bgcolor=color.new(color.yellow, 82), border_color=color.yellow, '
            f'text="OTE 61.8-78.6%", text_size=size.small)'
        )
    if eq:
        lines += [
            f'    line.new(bar_index-{left}, {eq}, bar_index+{future_bars}, {eq}, '
            f'color=color.white, style=line.style_dashed, width=1)',
            f'    label.new(bar_index, {eq}, "EQ 50%", '
            f'color=color.white, textcolor=color.black, style=label.style_label_left, size=size.tiny)',
        ]
    # Key fib lines
    for fib_key in ("0.0", "0.236", "0.382", "0.618", "0.786", "1.0"):
        price = key.get(fib_key)
        if price:
            lines += [
                f'    line.new(bar_index-{left}, {price}, bar_index+{future_bars}, {price}, '
                f'color=color.new(color.gray, 55), style=line.style_dotted, width=1)',
                f'    label.new(bar_index-{left}, {price}, "{fib_key}", '
                f'color=color.new(color.gray, 55), textcolor=color.white, '
                f'style=label.style_label_right, size=size.tiny)',
            ]
    ote_tag = " IN OTE!" if in_ote else ""
    lines.append(
        f'    label.new(bar_index, {cur}, "Loc: {loc}{ote_tag} | ratio: {fib_ratio:.3f}", '
        f'color=color.white, textcolor=color.black, style=label.style_label_left, size=size.small)'
    )
    return lines


def _compression_bounds(df: pd.DataFrame, start_ts: str, end_ts: str) -> tuple[float | None, float | None]:
    """Get the actual high/low of the price range during a compression window."""
    try:
        s = pd.Timestamp(start_ts, tz="UTC") if "+" not in start_ts and "Z" not in start_ts \
            else pd.Timestamp(start_ts)
        e = pd.Timestamp(end_ts,   tz="UTC") if "+" not in end_ts   and "Z" not in end_ts \
            else pd.Timestamp(end_ts)
        if s.tzinfo is None:
            s = s.tz_localize("UTC")
        if e.tzinfo is None:
            e = e.tz_localize("UTC")
        mask = (df.index >= s) & (df.index <= e)
        if not mask.any():
            return None, None
        return float(df.loc[mask, "high"].max()), float(df.loc[mask, "low"].min())
    except Exception:
        return None, None


def _pine_compression(result: dict, df: pd.DataFrame, future_bars: int) -> list[str]:
    if result.get("status"):
        return _nothing(f"Compression: {result['status']}")
    lines = []
    for c in result.get("compressions", []):
        age_end   = max(1, c["bars_since_end"])
        age_start = age_end + c["bars"] - 1
        ph, pl    = _compression_bounds(df, c["start_ts"], c["end_ts"])
        if ph is None:
            continue
        is_active = c["is_active"]
        bg = "color.new(color.yellow, 82)" if is_active else "color.new(color.gray, 82)"
        bc = "color.yellow"                if is_active else "color.gray"
        txt = (f"COMP {'active' if is_active else 'ended'} "
               f"{c['bars']}b sq:{c['squeeze_ratio']}x "
               f"tAtr:{c['tightest_range_atr']}")
        lines.append(
            f'    box.new(bar_index-{age_start}, {ph}, bar_index-{age_end}, {pl}, '
            f'bgcolor={bg}, border_color={bc}, text="{txt}", text_size=size.tiny)'
        )
    return lines or _nothing("No compressions detected")


def _pine_sponsored_candle(result: dict, future_bars: int) -> list[str]:
    if result.get("status"):
        return _nothing(f"Sponsored candle: {result['status']}")
    lines = []
    for z in result.get("candles", []):
        age      = max(1, int(z["age_bars"]))
        top, bot = z["high"], z["low"]
        ztype    = z["ob_type"]
        mit      = "mit" if z["is_mitigated"] else "active"
        sw_side  = z.get("sweep_side", "?")[:3]
        bg = "color.new(color.lime, 68)"    if ztype == "bullish" else "color.new(color.fuchsia, 68)"
        bc = "color.lime"                   if ztype == "bullish" else "color.fuchsia"
        arrow = "U" if ztype == "bullish" else "D"
        lines.append(
            f'    box.new(bar_index-{age}, {top}, bar_index+{future_bars}, {bot}, '
            f'bgcolor={bg}, border_color={bc}, '
            f'text="SpC{arrow} {mit} sw:{sw_side}", text_size=size.tiny)'
        )
    return lines or _nothing("No sponsored candles detected")


def _pine_absorption_poi(result: dict, future_bars: int) -> list[str]:
    poi_zone = result.get("poi_zone")
    poi_type = result.get("poi_type", "none")
    reversal = result.get("reversal_direction", "none")
    absorbed = result.get("absorption_detected", False)
    poi_hit  = result.get("poi_hit", False)
    if not poi_zone or poi_type == "none":
        return _nothing(f"No POI absorption — poi_type: {poi_type} poi_hit: {poi_hit}")
    ph = poi_zone["high"]
    pl = poi_zone["low"]
    bg = "color.new(color.yellow, 72)" if absorbed else "color.new(color.gray, 75)"
    bc = "color.yellow"                if absorbed else "color.gray"
    txt = f"Abs:{'YES' if absorbed else 'no'} | {poi_type} | rev:{reversal}"
    lines = [
        f'    box.new(bar_index-5, {ph}, bar_index+{future_bars}, {pl}, '
        f'bgcolor={bg}, border_color={bc}, text="{txt}", text_size=size.small)',
    ]
    detail = result.get("absorption_detail", {})
    if detail:
        mid = round((ph + pl) / 2, 2)
        vr  = detail.get("vol_ratio", 0)
        cp  = detail.get("close_position", 0)
        ar  = detail.get("range_atr_ratio", 0)
        lines.append(
            f'    label.new(bar_index+{future_bars+1}, {mid}, '
            f'"vol_ratio:{vr:.2f} close_pos:{cp:.2f} atr_ratio:{ar:.2f}", '
            f'style=label.style_label_left, color=color.black, textcolor=color.white, size=size.tiny)'
        )
    return lines


def _pine_cumulative_delta(result: dict, df: pd.DataFrame, future_bars: int) -> list[str]:
    if result.get("status"):
        return _nothing(f"Cumulative delta: {result['status']}")
    lines = []
    trend = result.get("delta_trend", "neutral")
    delta = result.get("session_delta", 0)
    tc    = "color.green" if trend == "positive" else ("color.red" if trend == "negative" else "color.gray")
    lines.append(
        f'    label.new(bar_index+1, close, "CD session:{delta:.1f} trend:{trend}", '
        f'color={tc}, textcolor=color.white, style=label.style_label_left, size=size.small)'
    )
    for div in result.get("divergences", []):
        dtype  = div["type"]
        bar_ts = div.get("bar_ts")
        price  = div.get("price_high") or div.get("price_low") or 0
        if not (price and bar_ts):
            continue
        age   = _ts_to_age(df, bar_ts)
        dc    = "color.red"   if dtype == "bearish" else "color.green"
        ds    = "label.style_triangledown" if dtype == "bearish" else "label.style_triangleup"
        lines.append(
            f'    label.new(bar_index-{age}, {price}, "CD div {dtype}", '
            f'color={dc}, textcolor=color.white, style={ds}, size=size.small)'
        )
    if len(lines) == 1:
        lines.append(_nothing("No CD divergences")[0])
    return lines


def _pine_cd_divergence(result: dict, df: pd.DataFrame, future_bars: int) -> list[str]:
    if result.get("reason"):
        return _nothing(f"CDdiv: {result['reason']}")
    detected    = result.get("divergence_detected", False)
    dtype       = result.get("type", "none")
    at_struct   = result.get("at_structure", False)
    level       = result.get("structure_level")
    struct_type = result.get("structure_type", "")
    strength    = result.get("signal_strength", "none")
    sweep_prec  = result.get("sweep_preceded", False)
    sweep_ts    = result.get("sweep_ts")
    if not (detected and level):
        return _nothing(
            f"No CD div at structure | type:{dtype} at_struct:{at_struct} strength:{strength}"
        )
    bc = "color.red" if dtype == "bearish" else "color.green"
    txt = f"CD {dtype} @ {struct_type} | {strength}{' | swept' if sweep_prec else ''}"
    lines = [
        f'    line.new(0, {level}, bar_index+{future_bars}, {level}, '
        f'color={bc}, style=line.style_dashed, width=2)',
        f'    label.new(bar_index, {level}, "{txt}", '
        f'color={bc}, textcolor=color.white, style=label.style_label_left, size=size.small)',
    ]
    if sweep_prec and sweep_ts:
        age = _ts_to_age(df, sweep_ts)
        lines.append(
            f'    label.new(bar_index-{age}, {level}, "SWEEP", '
            f'color=color.orange, textcolor=color.black, style=label.style_label_up, size=size.tiny)'
        )
    return lines


def _pine_killzone(result: dict) -> list[str]:
    kz      = result.get("active_killzone") or "none"
    next_kz = result.get("next_killzone") or "—"
    t_str   = result.get("kyiv_time", "")
    weekday = result.get("weekday", "")
    ott     = result.get("in_ott_window", False)
    is_fri  = result.get("is_friday", False)
    kz_c    = "color.yellow" if kz != "none" else "color.gray"
    ott_c   = "color.yellow" if ott else "color.gray"
    fri_c   = "color.orange" if is_fri else "color.gray"
    return [
        f'    var _kzt = table.new(position.top_right, 2, 5, '
        f'bgcolor=color.new(color.black, 80), frame_color=color.gray, frame_width=1)',
        f'    table.cell(_kzt, 0, 0, "Killzone",  text_color=color.white, text_size=size.small)',
        f'    table.cell(_kzt, 1, 0, "{kz}",       text_color={kz_c}, text_size=size.small)',
        f'    table.cell(_kzt, 0, 1, "Kyiv time",  text_color=color.white, text_size=size.small)',
        f'    table.cell(_kzt, 1, 1, "{t_str} {weekday}", text_color=color.white, text_size=size.small)',
        f'    table.cell(_kzt, 0, 2, "OTT window", text_color=color.white, text_size=size.small)',
        f'    table.cell(_kzt, 1, 2, "{"YES" if ott else "no"}", text_color={ott_c}, text_size=size.small)',
        f'    table.cell(_kzt, 0, 3, "Next KZ",    text_color=color.white, text_size=size.small)',
        f'    table.cell(_kzt, 1, 3, "{next_kz}",  text_color=color.white, text_size=size.small)',
        f'    table.cell(_kzt, 0, 4, "Friday",     text_color=color.white, text_size=size.small)',
        f'    table.cell(_kzt, 1, 4, "{"YES" if is_fri else "no"}", text_color={fri_c}, text_size=size.small)',
    ]


def _pine_multi_tf(result: dict, htf: str, ltf: str) -> list[str]:
    aligned = result.get("aligned", False)
    bias    = result.get("htf_bias", "unknown")
    role    = result.get("ltf_role", "unknown")
    sync    = result.get("sync_quality", "unknown")
    al_c    = "color.green" if aligned else "color.red"
    bias_c  = "color.green" if bias == "bullish" else ("color.red" if bias == "bearish" else "color.gray")
    sync_c  = {"strong": "color.green", "weak": "color.orange", "desync": "color.red"}.get(sync, "color.gray")
    return [
        f'    var _mtft = table.new(position.top_left, 2, 4, '
        f'bgcolor=color.new(color.black, 80), frame_color=color.gray, frame_width=1)',
        f'    table.cell(_mtft, 0, 0, "MTF Align ({htf}/{ltf})", text_color=color.white, text_size=size.small)',
        f'    table.cell(_mtft, 1, 0, "{"YES" if aligned else "NO"}", text_color={al_c}, text_size=size.small)',
        f'    table.cell(_mtft, 0, 1, "HTF bias ({htf})",          text_color=color.white, text_size=size.small)',
        f'    table.cell(_mtft, 1, 1, "{bias}",                    text_color={bias_c}, text_size=size.small)',
        f'    table.cell(_mtft, 0, 2, "LTF role ({ltf})",          text_color=color.white, text_size=size.small)',
        f'    table.cell(_mtft, 1, 2, "{role}",                    text_color=color.white, text_size=size.small)',
        f'    table.cell(_mtft, 0, 3, "Sync quality",              text_color=color.white, text_size=size.small)',
        f'    table.cell(_mtft, 1, 3, "{sync}",                    text_color={sync_c}, text_size=size.small)',
    ]


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run detectors on BTCUSDT spot and write one Pine Script file per detector.",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument("--symbol",   default="BTCUSDT", help="Trading pair (default: BTCUSDT)")
    parser.add_argument("--tf",       default="30m",
                        choices=sorted(VALID_TIMEFRAMES),
                        help="Timeframe (default: 30m)")
    parser.add_argument("--bars",     default=500, type=int, help="Number of bars (default: 500)")
    parser.add_argument("--future",   default=50,  type=int, help="Future bars to extend zones (default: 50)")
    parser.add_argument("--out",      default="./pine_debug", help="Output directory (default: ./pine_debug)")
    parser.add_argument("--detector", default=None, metavar="NAME",
                        help="Run only this detector (default: run all).\nSee available names with --list.")
    parser.add_argument("--list",     action="store_true",
                        help="Print all available detector names and exit.")
    args = parser.parse_args()

    # ── --list ────────────────────────────────────────────────────────────────
    if args.list:
        print("Available detectors:")
        for name in _ALL_DETECTOR_NAMES:
            print(f"  {name}")
        return

    # ── --detector validation ─────────────────────────────────────────────────
    selected: str | None = args.detector
    if selected is not None and selected not in _ALL_DETECTOR_NAMES:
        print(f"error: unknown detector '{selected}'")
        print(f"Available: {', '.join(_ALL_DETECTOR_NAMES)}")
        sys.exit(1)

    # Set of names that will actually run (all, or just one)
    active_names: frozenset[str] = (
        frozenset({selected}) if selected else frozenset(_ALL_DETECTOR_NAMES)
    )

    symbol      = args.symbol.upper()
    tf          = args.tf
    bars        = args.bars
    future_bars = args.future
    out_dir     = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    htf = _HTF_MAP.get(tf, "4h")

    # ── Fetch data — only what the selected detector(s) actually need ─────────
    print(f"Fetching {symbol} spot — {tf} × {bars} bars …")
    source = BinanceSource(market="spot")
    df = source.get_ohlc(symbol, tf, bars)
    print(f"  OK — {len(df)} bars  {df.index[0]}  →  {df.index[-1]}")

    df_delta = df  # default fallback; replaced below if needed
    if active_names & _NEEDS_DELTA:
        print(f"Fetching delta data ({tf}) …")
        try:
            df_delta = fetch_ohlcv_with_delta(symbol, tf, bars, market="spot")
            print(f"  OK — delta columns: {list(df_delta.columns)}")
        except Exception as exc:
            print(f"  WARNING: delta fetch failed ({exc}). CD detectors will show error label.")

    htf_ms_result: dict = {}
    ltf_ms_result: dict = {}
    if active_names & (_NEEDS_HTF | _NEEDS_MS):
        ltf_ms_result = detect_market_structure(df)
    if active_names & _NEEDS_HTF and htf != tf:
        print(f"Fetching HTF data ({htf}) for multi-TF alignment …")
        try:
            df_htf = source.get_ohlc(symbol, htf, 200)
            htf_ms_result = detect_market_structure(df_htf)
        except Exception as exc:
            print(f"  WARNING: HTF fetch failed ({exc}).")
            htf_ms_result = ltf_ms_result
    elif active_names & _NEEDS_HTF:
        htf_ms_result = ltf_ms_result

    # ── Build task list ───────────────────────────────────────────────────────
    # Each entry: (detector_name, run_callable, pine_callable)
    tasks = [
        ("detect_fvg",
            lambda: detect_fvg(df),
            lambda r: _pine_fvg(r, future_bars)),

        ("detect_order_block",
            lambda: detect_order_block(df),
            lambda r: _pine_order_block(r, future_bars)),

        ("detect_ifvg",
            lambda: detect_ifvg(df),
            lambda r: _pine_ifvg(r, future_bars)),

        ("detect_breaker_block",
            lambda: detect_breaker_block(df),
            lambda r: _pine_breaker_block(r, future_bars)),

        ("detect_rejection_block",
            lambda: detect_rejection_block(df),
            lambda r: _pine_rejection_block(r, future_bars)),

        ("detect_mitigation_block",
            lambda: detect_mitigation_block(df),
            lambda r: _pine_mitigation_block(r, future_bars)),

        ("detect_liquidity",
            lambda: detect_liquidity(df),
            lambda r: _pine_liquidity(r, df, future_bars)),

        ("detect_bos",
            lambda: detect_bos(df),
            lambda r: _pine_bos(r, df, future_bars)),

        ("detect_volume_profile",
            lambda: detect_volume_profile(df),
            lambda r: _pine_volume_profile(r, bars, future_bars)),

        ("detect_market_structure",
            lambda: detect_market_structure(df),
            lambda r: _pine_market_structure(r, df, future_bars)),

        ("detect_fractals",
            lambda: detect_fractals(df),
            lambda r: _pine_fractals(r, future_bars)),

        ("detect_fib_zones",
            lambda: detect_fib_zones(
                df,
                swing_high=ltf_ms_result.get("last_swing_high", {}).get("price") or float(df["high"].max()),
                swing_low =ltf_ms_result.get("last_swing_low",  {}).get("price") or float(df["low"].min()),
            ),
            lambda r: _pine_fib_zones(r, bars, future_bars)),

        ("detect_compression",
            lambda: detect_compression(df),
            lambda r: _pine_compression(r, df, future_bars)),

        ("detect_sponsored_candle",
            lambda: detect_sponsored_candle(df),
            lambda r: _pine_sponsored_candle(r, future_bars)),

        ("check_absorption_at_poi",
            lambda: check_absorption_at_poi(df),
            lambda r: _pine_absorption_poi(r, future_bars)),

        ("detect_cumulative_delta",
            lambda: detect_cumulative_delta(df_delta),
            lambda r: _pine_cumulative_delta(r, df, future_bars)),

        ("check_cd_divergence_at_structure",
            lambda: check_cd_divergence_at_structure(df_delta),
            lambda r: _pine_cd_divergence(r, df, future_bars)),

        ("current_killzone",
            lambda: current_killzone(),
            lambda r: _pine_killzone(r)),

        ("check_multi_tf_alignment",
            lambda: check_multi_tf_alignment(
                htf_state=htf_ms_result.get("state", "ranging"),
                ltf_state=ltf_ms_result.get("state", "ranging"),
                htf_timeframe=htf,
                ltf_timeframe=tf,
            ),
            lambda r: _pine_multi_tf(r, htf, tf)),
    ]

    # ── Filter to selected detector(s) ───────────────────────────────────────
    tasks = [t for t in tasks if t[0] in active_names]

    # ── Run detectors in parallel, save sequentially ──────────────────────────
    print(f"\nRunning {len(tasks)} detector{'s' if len(tasks) != 1 else ''} …")
    results: dict[str, dict] = {}
    with ThreadPoolExecutor(max_workers=8) as ex:
        futures = {ex.submit(run_fn): name for name, run_fn, _ in tasks}
        for fut in futures:
            name = futures[fut]
            try:
                results[name] = fut.result(timeout=30)
            except Exception as exc:
                print(f"  ERROR  {name}: {exc}")
                results[name] = {"status": "error", "error": str(exc)}

    saved = 0
    errors = 0
    print()
    for name, run_fn, pine_fn in tasks:
        result = results.get(name, {})
        try:
            body  = pine_fn(result)
            hdr   = _header(symbol, tf, name, future_bars)
            pine  = _assemble(hdr, body)
            fname = f"{name}_{symbol}_{tf}.pine"
            (out_dir / fname).write_text(pine, encoding="utf-8")
            status = result.get("status", "ok")
            count_key = next(
                (k for k in ("count_active", "count", "compressions") if k in result), None
            )
            count_str = f" ({result[count_key]} zones)" if count_key and isinstance(result.get(count_key), int) else ""
            print(f"  OK     {fname}  [{status}{count_str}]")
            saved += 1
        except Exception as exc:
            print(f"  ERROR  {name}: {exc}")
            errors += 1

    print(f"\n{'─'*60}")
    print(f"Saved {saved} Pine Script files → {out_dir.resolve()}")
    if errors:
        print(f"Errors: {errors}")
    print(
        "\nHow to use:"
        "\n  1. Open TradingView and switch the chart to "
        f"{symbol} {tf}"
        "\n  2. Open Pine Script Editor → New indicator → paste file content → Save"
        "\n  3. Click 'Add to chart' — zones appear on the last bar"
        "\n  4. Load one file per detector tab for side-by-side comparison"
    )


if __name__ == "__main__":
    main()
