"""
Pine Script v5 generator.

Runs all Tier A + B detectors on the provided DataFrame and emits a
ready-to-paste Pine Script overlay indicator that draws every detected zone
on the user's TradingView chart.

Usage (MCP / CLI):
  1. Call generate_pine_script(symbol="BTCUSDT", timeframe="1h")
  2. Copy the returned `pine_script` string into TradingView:
     Pine Script Editor → New script → paste → "Add to chart"
  3. All zones appear immediately. Zones extend `future_bars` bars to the right
     so they're visible at the current price.

Zone color legend:
  Teal   = Bullish FVG        Red      = Bearish FVG
  Blue   = Bullish OB         Orange   = Bearish OB
  Lime   = Bullish IFVG       Maroon   = Bearish IFVG
  Aqua   = Bullish Breaker    Fuchsia  = Bearish Breaker
  Green  = Bullish Mitigation Dark red = Bearish Mitigation
  Navy   = Bullish Rejection  Purple   = Bearish Rejection
  Yellow dashed = BSL pool    Purple dashed = SSL pool
  Green/Red solid thin = BOS level
"""

from __future__ import annotations

from datetime import datetime, timezone

import pandas as pd

from copilot.detectors.bos import detect_bos
from copilot.detectors.breaker_block import detect_breaker_block
from copilot.detectors.fvg import detect_fvg
from copilot.detectors.ifvg import detect_ifvg
from copilot.detectors.liquidity import detect_liquidity
from copilot.detectors.mitigation_block import detect_mitigation_block
from copilot.detectors.order_block import detect_order_block
from copilot.detectors.rejection_block import detect_rejection_block

TOOL_SCHEMA = {
    "name": "generate_pine_script",
    "description": (
        "Run all detectors and generate a Pine Script v5 overlay indicator "
        "that draws every detected zone (FVGs, OBs, IFVGs, Breakers, Mitigation Blocks, "
        "Rejection Blocks, liquidity levels, BOS marker) on a TradingView chart. "
        "Returns the full Pine Script code as a string. "
        "Paste it into TradingView → Pine Script Editor → New script → Add to chart. "
        "Use at the end of any analysis to give the trader a visual summary."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "symbol": {"type": "string", "description": "e.g. BTCUSDT"},
            "timeframe": {
                "type": "string",
                "enum": ["1m", "3m", "5m", "15m", "1h", "4h", "1d"],
            },
            "future_bars": {
                "type": "integer",
                "default": 50,
                "description": "How many bars to the right zone boxes extend (default 50)",
            },
        },
        "required": ["symbol", "timeframe"],
    },
}


def generate_pine_script(
    df: pd.DataFrame,
    symbol: str = "UNKNOWN",
    timeframe: str = "?",
    future_bars: int = 50,
) -> dict:
    """Run all detectors and emit a Pine Script v5 overlay."""
    # ── Run detectors ────────────────────────────────────────────────────────
    fvgs       = detect_fvg(df)
    obs        = detect_order_block(df)
    liq        = detect_liquidity(df)
    bos        = detect_bos(df)
    ifvgs      = detect_ifvg(df)
    breakers   = detect_breaker_block(df)
    rejections = detect_rejection_block(df)
    mitigations = detect_mitigation_block(df)

    # ── Compute TF bar duration for sweep age calculation ────────────────────
    tf_seconds = float((df.index[1] - df.index[0]).total_seconds()) if len(df) > 1 else 3600.0

    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = []

    # ── Header ───────────────────────────────────────────────────────────────
    lines += [
        f"// Generated by Trading Co-Pilot — {symbol} {timeframe} — {now_str}",
        "//@version=5",
        f'indicator("Co-Pilot: {symbol} {timeframe}", overlay=true, '
        "max_boxes_count=200, max_lines_count=500, max_labels_count=200)",
        "",
        "// ── Zone colors ─────────────────────────────────────────────────────────",
        "c_fvg_bull  = color.new(color.teal,    80)",
        "c_fvg_bear  = color.new(color.red,     80)",
        "c_ob_bull   = color.new(color.blue,    75)",
        "c_ob_bear   = color.new(color.orange,  75)",
        "c_ifvg_bull = color.new(color.lime,    70)",
        "c_ifvg_bear = color.new(color.maroon,  70)",
        "c_brk_bull  = color.new(color.aqua,    70)",
        "c_brk_bear  = color.new(color.fuchsia, 70)",
        "c_mit_bull  = color.new(color.green,   65)",
        "c_mit_bear  = color.new(#8B0000,       65)  // dark red",
        "c_rej_bull  = color.new(color.navy,    70)",
        "c_rej_bear  = color.new(color.purple,  70)",
        "c_bsl       = color.new(color.yellow,   0)",
        "c_ssl       = color.new(color.purple,   0)",
        "",
        "if barstate.islast",
    ]

    zone_count = 0

    # ── Fair Value Gaps ───────────────────────────────────────────────────────
    fvg_list = fvgs.get("fvgs", [])
    if fvg_list:
        lines.append("    // FVGs")
        for z in fvg_list:
            age   = max(1, int(z["age_bars"]))
            top   = z["upper"]
            bot   = z["lower"]
            ztype = z["type"]
            state = z.get("fill_state", "untouched")
            bg    = "c_fvg_bull"  if ztype == "bullish" else "c_fvg_bear"
            bc    = "color.teal"  if ztype == "bullish" else "color.red"
            arrow = "\u2191" if ztype == "bullish" else "\u2193"
            label = f"FVG{arrow} {state}"
            lines.append(
                f'    box.new(bar_index-{age}, {top}, bar_index+{future_bars}, {bot}, '
                f'bgcolor={bg}, border_color={bc}, text="{label}", text_size=size.tiny)'
            )
            zone_count += 1

    # ── Inverted FVGs ─────────────────────────────────────────────────────────
    ifvg_list = ifvgs.get("ifvgs", [])
    if ifvg_list:
        lines.append("    // IFVGs")
        for z in ifvg_list:
            age   = max(1, int(z["age_bars"]))
            top   = z["upper"]
            bot   = z["lower"]
            ztype = z["type"]
            tested = "tested" if z["is_tested"] else "untested"
            bg    = "c_ifvg_bull" if ztype == "bullish" else "c_ifvg_bear"
            bc    = "color.lime"  if ztype == "bullish" else "color.maroon"
            arrow = "\u2191" if ztype == "bullish" else "\u2193"
            label = f"IFVG{arrow} {tested}"
            lines.append(
                f'    box.new(bar_index-{age}, {top}, bar_index+{future_bars}, {bot}, '
                f'bgcolor={bg}, border_color={bc}, text="{label}", text_size=size.tiny)'
            )
            zone_count += 1

    # ── Order Blocks ──────────────────────────────────────────────────────────
    ob_list = obs.get("obs", [])
    if ob_list:
        lines.append("    // Order Blocks")
        for z in ob_list:
            age   = max(1, int(z["age_bars"]))
            top   = z["high"]
            bot   = z["low"]
            ztype = z["type"]
            mit   = "mit" if z["is_mitigated"] else "active"
            fvgm  = "+FVG" if z["has_fvg_after"] else ""
            bg    = "c_ob_bull"   if ztype == "bullish" else "c_ob_bear"
            bc    = "color.blue"  if ztype == "bullish" else "color.orange"
            arrow = "\u2191" if ztype == "bullish" else "\u2193"
            label = f"OB{arrow}{fvgm} {mit}"
            lines.append(
                f'    box.new(bar_index-{age}, {top}, bar_index+{future_bars}, {bot}, '
                f'bgcolor={bg}, border_color={bc}, text="{label}", text_size=size.tiny)'
            )
            zone_count += 1

    # ── Breaker Blocks ────────────────────────────────────────────────────────
    brk_list = breakers.get("breakers", [])
    if brk_list:
        lines.append("    // Breaker Blocks")
        for z in brk_list:
            age   = max(1, int(z["age_bars"]))
            top   = z["high"]
            bot   = z["low"]
            ztype = z["type"]
            tested = "tested" if z["is_tested"] else "untested"
            bg    = "c_brk_bull"  if ztype == "bullish" else "c_brk_bear"
            bc    = "color.aqua"  if ztype == "bullish" else "color.fuchsia"
            arrow = "\u2191" if ztype == "bullish" else "\u2193"
            label = f"BRK{arrow} {tested}"
            lines.append(
                f'    box.new(bar_index-{age}, {top}, bar_index+{future_bars}, {bot}, '
                f'bgcolor={bg}, border_color={bc}, text="{label}", text_size=size.tiny)'
            )
            zone_count += 1

    # ── Mitigation Blocks ─────────────────────────────────────────────────────
    mit_list = [b for b in mitigations.get("blocks", []) if not b["is_mitigated"]]
    if mit_list:
        lines.append("    // Mitigation Blocks (unmitigated)")
        for z in mit_list:
            age   = max(1, int(z["age_bars"]))
            top   = z["high"]
            bot   = z["low"]
            ztype = z["type"]
            bg    = "c_mit_bull" if ztype == "bullish" else "c_mit_bear"
            bc    = "color.green" if ztype == "bullish" else "#8B0000"
            arrow = "\u2191" if ztype == "bullish" else "\u2193"
            label = f"MitB{arrow}"
            lines.append(
                f'    box.new(bar_index-{age}, {top}, bar_index+{future_bars}, {bot}, '
                f'bgcolor={bg}, border_color={bc}, text="{label}", text_size=size.tiny)'
            )
            zone_count += 1

    # ── Rejection Blocks ──────────────────────────────────────────────────────
    rej_list = [b for b in rejections.get("blocks", []) if not b["is_mitigated"]]
    if rej_list:
        lines.append("    // Rejection Blocks (unmitigated)")
        for z in rej_list:
            age   = max(1, int(z["age_bars"]))
            top   = z["high"]
            bot   = z["low"]
            ztype = z["type"]
            bg    = "c_rej_bull"  if ztype == "bullish" else "c_rej_bear"
            bc    = "color.navy"  if ztype == "bullish" else "color.purple"
            arrow = "\u2191" if ztype == "bullish" else "\u2193"
            label = f"RejB{arrow}"
            lines.append(
                f'    box.new(bar_index-{age}, {top}, bar_index+{future_bars}, {bot}, '
                f'bgcolor={bg}, border_color={bc}, text="{label}", text_size=size.tiny)'
            )
            zone_count += 1

    # ── Liquidity Pools ───────────────────────────────────────────────────────
    bsl = liq.get("buyside_liquidity", [])
    ssl = liq.get("sellside_liquidity", [])
    if bsl or ssl:
        lines.append("    // Liquidity levels")
        for pool in bsl:
            age   = max(1, int(pool["age_bars"]))
            price = pool["price"]
            ptype = pool["type"]
            lines.append(
                f'    line.new(bar_index-{age}, {price}, bar_index+{future_bars}, {price}, '
                f'color=c_bsl, style=line.style_dashed, width=2)'
            )
            lines.append(
                f'    label.new(bar_index-{age}, {price}, "BSL {price} ({ptype})", '
                f'color=c_bsl, textcolor=color.black, style=label.style_label_right, size=size.tiny)'
            )
            zone_count += 1
        for pool in ssl:
            age   = max(1, int(pool["age_bars"]))
            price = pool["price"]
            ptype = pool["type"]
            lines.append(
                f'    line.new(bar_index-{age}, {price}, bar_index+{future_bars}, {price}, '
                f'color=c_ssl, style=line.style_dashed, width=2)'
            )
            lines.append(
                f'    label.new(bar_index-{age}, {price}, "SSL {price} ({ptype})", '
                f'color=c_ssl, textcolor=color.white, style=label.style_label_right, size=size.tiny)'
            )
            zone_count += 1

    # ── Confirmed Sweeps ──────────────────────────────────────────────────────
    sweeps = liq.get("recent_sweeps", [])
    if sweeps:
        lines.append("    // Confirmed sweeps (triangle markers)")
        for sweep in sweeps:
            try:
                ts = pd.Timestamp(sweep["sweep_ts"])
                if ts.tzinfo is None:
                    ts = ts.tz_localize("UTC")
                age = int((df.index[-1] - ts).total_seconds() / tf_seconds)
                age = max(1, age)
            except Exception:
                continue
            level = sweep["swept_level"]
            side  = sweep["side"]
            color = "color.yellow" if side == "buyside" else "color.purple"
            style = "label.style_triangleup" if side == "sellside" else "label.style_triangledown"
            arrow = "\u2191" if side == "sellside" else "\u2193"
            label = f"SW{arrow}"
            lines.append(
                f'    label.new(bar_index-{age}, {level}, "{label}", '
                f'color={color}, textcolor=color.black, style={style}, size=size.small)'
            )

    # ── Most Recent BOS / MSS marker ─────────────────────────────────────────
    bos_type = bos.get("type", "none")
    if bos_type not in (None, "none"):
        bos_dir   = bos.get("direction", "")
        bos_level = bos.get("broken_level")
        if bos_level:
            bc = "color.green" if bos_dir == "bullish" else "color.red"
            label = f"{bos_type} {bos_dir}"
            lines += [
                "    // Most recent BOS/MSS",
                f'    line.new(bar_index-2, {bos_level}, bar_index+{future_bars}, {bos_level}, '
                f'color={bc}, style=line.style_solid, width=1)',
                f'    label.new(bar_index, {bos_level}, "{label}", '
                f'color={bc}, textcolor=color.white, style=label.style_label_left, size=size.small)',
            ]

    # ── Footer comment ────────────────────────────────────────────────────────
    lines += [
        "",
        f"// ── Summary: {zone_count} zones drawn ─────────────────────────────────────────",
        f"// FVGs: {fvgs.get('count_active', 0)}"
        f"  OBs: {obs.get('count', 0)}"
        f"  IFVGs: {ifvgs.get('count', 0)}"
        f"  Breakers: {breakers.get('count', 0)}",
        f"// BSL pools: {len(bsl)}"
        f"  SSL pools: {len(ssl)}"
        f"  BOS: {bos_type}",
    ]

    pine_script = "\n".join(lines)

    return {
        "pine_script": pine_script,
        "instructions": (
            "Copy the pine_script value into TradingView: "
            "Pine Script Editor → New script → paste → Save → Add to chart. "
            f"Switch chart to {symbol} {timeframe} first."
        ),
        "zone_count": zone_count,
        "summary": {
            "fvgs": fvgs.get("count_active", 0),
            "obs": obs.get("count", 0),
            "ifvgs": ifvgs.get("count", 0),
            "breakers": breakers.get("count", 0),
            "mitigation_blocks": len(mit_list),
            "rejection_blocks": len(rej_list),
            "bsl_pools": len(bsl),
            "ssl_pools": len(ssl),
            "sweeps": len(sweeps),
            "bos": bos_type,
        },
    }
