"""
Per-detector Pine Script v5 body generators.

Moved verbatim out of `scripts/debug_detectors.py` (P3, Aug 2026) so the same
emitters feed both the debug CLI and the copilot's `generate_pine_script` tool.
The bodies were visually verified against TradingView during P2-1/P2-2 — they
are transplanted unchanged; only the dispatch layer below them is new.

Each `_pine_*` function returns a list of 4-space-indented Pine lines meant to
sit inside an `if barstate.islast` block, and anchors every drawing to `anchor`
(the last CLOSED bar — see `overlay.build_overlay` / `file_header`).

Signatures differ per detector (some need the DataFrame, some the bar count).
`EMITTERS` normalises them to one shape: (result, EmitContext) -> list[str].

Visual style: B&W design system.
  c_fvg_fill     #f7525f 15%  — FVG / IFVG fill
  c_fvg_line     #f7525f 100% — FVG center line, IFVG border, bearish events
  c_block_active #4a4a4a 15%  — All blocks (active)
  c_block_mit    #4a4a4a 5%   — All blocks (mitigated)
  c_structure    #000000 100% — BOS, liquidity lines, swing markers
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Callable

import pandas as pd


def _now_str() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _header(symbol: str, tf: str, indicator_name: str, future_bars: int) -> list[str]:
    return [
        f"// Generated by debug_detectors.py — {symbol} {tf} — {indicator_name} — {_now_str()}",
        "//@version=5",
        f'indicator("Debug: {indicator_name} | {symbol} {tf}", overlay=true, '
        "max_boxes_count=500, max_lines_count=500, max_labels_count=500)",
        "",
        "// ── Design system — B&W preset ───────────────────────────────────────────────",
        "c_fvg_fill     = color.new(#f7525f, 85)   // FVG / IFVG fill (15%)",
        "c_fvg_line     = color.new(#f7525f,  0)   // FVG center line, IFVG border, bearish",
        "c_block_active = color.new(#4a4a4a, 85)   // Blocks active (15%)",
        "c_block_mit    = color.new(#4a4a4a, 95)   // Blocks mitigated (5%)",
        "c_structure    = color.new(#000000,  0)   // BOS, liquidity, swing markers",
        "c_vp_hvn       = color.new(#4a4a4a, 40)   // VP HVN bars",
        "c_vp_lvn       = color.new(#4a4a4a, 80)   // VP LVN bars",
        "c_vp_poc       = color.new(#f7525f, 35)   // VP POC bar",
        'show_labels    = input.bool(true, "Show labels")',
        'drop_forming   = input.bool(true, "Source data drops the forming bar (shift anchor left 1)")',
        "",
        "if barstate.islast",
        # All drawings anchor to `anchor`, the last CLOSED bar. The detector data
        # excludes the forming candle, but on a live chart barstate.islast fires on
        # the forming bar — so the script's last bar = bar_index-1. Without this the
        # whole overlay is shifted +1 bar to the right.
        "    anchor = bar_index - (drop_forming ? 1 : 0)",
    ]


def _ts_to_age(df: pd.DataFrame, ts_str: str) -> int:
    """Return how many bars ago *ts_str* occurred relative to the last bar."""
    try:
        ts = pd.Timestamp(ts_str)
        if ts.tzinfo is None:
            ts = ts.tz_localize("UTC")
        tf_sec = float((df.index[1] - df.index[0]).total_seconds())
        return max(1, int((df.index[-1] - ts).total_seconds() / tf_sec))
    except Exception:
        return 1


def _nothing(msg: str) -> list[str]:
    return [
        f'    label.new(anchor, close, "{msg}", '
        f'style=label.style_label_left, color=c_block_active, '
        f'textcolor=color.white, size=size.small)'
    ]


def _assemble(header: list[str], body: list[str]) -> str:
    return "\n".join(header + body)


# ── Per-detector Pine Script body generators ──────────────────────────────────
# Each function returns a list[str] of indented Pine Script lines (4-space).
# They go inside the `if barstate.islast` block produced by _header().

# ── FVG ──────────────────────────────────────────────────────────────────────

def _pine_fvg(result: dict, future_bars: int) -> list[str]:
    """
    B&W style: c_fvg_fill box (no border) + solid c_fvg_line center line.
    fill_state and fill_percentage shown in label (guarded by show_labels).
    """
    lines = []
    for z in result.get("fvgs", []):
        # age_bars anchors C2 (i+2); the gap belongs to the C1 impulse candle, so
        # shift the left edge one bar left to sit on C1.
        age      = max(1, int(z["age_bars"])) + 1
        top, bot = z["upper"], z["lower"]
        mid      = round((top + bot) / 2, 2)
        ztype    = z["type"]
        state    = z.get("fill_state", "untouched")
        pct      = z.get("fill_percentage", 0)
        arrow    = "↑" if ztype == "bullish" else "↓"
        # Fill box — no border
        lines.append(
            f'    box.new(anchor-{age}, {top}, anchor+{future_bars}, {bot}, '
            f'bgcolor=c_fvg_fill, border_color=color.new(color.white, 100))'
        )
        # Center line — distinguishes FVG from IFVG
        lines.append(
            f'    line.new(anchor-{age}, {mid}, anchor+{future_bars}, {mid}, '
            f'color=c_fvg_line, style=line.style_solid, width=1)'
        )
        # Debug label: fill state + fill %
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor-{age}+1, {top}, '
            f'"FVG{arrow} {state} {pct:.0f}%", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.tiny)'
        )
    return lines or _nothing("No FVGs detected")


# ── IFVG ─────────────────────────────────────────────────────────────────────

def _pine_ifvg(result: dict, future_bars: int) -> list[str]:
    """
    B&W style: c_fvg_fill box with DASHED c_fvg_line border. NO center line
    (dashed border is the visual distinction from FVG).
    """
    lines = []
    for z in result.get("ifvgs", []):
        # See _pine_fvg: anchor the box on the C1 gap candle, not C2.
        age      = max(1, int(z["age_bars"])) + 1
        top, bot = z["upper"], z["lower"]
        ztype    = z["type"]
        tested   = "tested" if z["is_tested"] else "untested"
        arrow    = "↑" if ztype == "bullish" else "↓"
        lines.append(
            f'    box.new(anchor-{age}, {top}, anchor+{future_bars}, {bot}, '
            f'bgcolor=c_fvg_fill, border_color=c_fvg_line, '
            f'border_style=line.style_dashed, border_width=1)'
        )
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor-{age}+1, {top}, "IFVG{arrow} {tested}", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.tiny)'
        )
    return lines or _nothing("No IFVGs detected")


# ── Order Blocks ──────────────────────────────────────────────────────────────

def _pine_order_block(result: dict, future_bars: int) -> list[str]:
    """
    Active: c_block_active (extends right).  Mitigated: c_block_mit (ends at anchor).
    has_fvg_after shown as +FVG suffix.
    """
    lines = []
    for z in result.get("obs", []):
        age      = max(1, int(z["age_bars"]))
        top, bot = z["high"], z["low"]
        ztype    = z["type"]
        mit      = z.get("is_mitigated", False)
        fvgm     = "+FVG" if z.get("has_fvg_after") else ""
        arrow    = "↑" if ztype == "bullish" else "↓"
        label    = f"OB{arrow}{fvgm}"
        if mit:
            lines.append(
                f'    box.new(anchor-{age}, {top}, anchor, {bot}, '
                f'bgcolor=c_block_mit, border_color=color.new(color.white, 100))'
            )
            lines.append(f'    if show_labels')
            lines.append(
                f'        label.new(anchor-{age}+1, {top}, "{label} mit", '
                f'color=color.new(color.white, 100), textcolor=color.black, '
                f'style=label.style_none, size=size.tiny)'
            )
        else:
            lines.append(
                f'    box.new(anchor-{age}, {top}, anchor+{future_bars}, {bot}, '
                f'bgcolor=c_block_active, border_color=color.new(color.white, 100))'
            )
            lines.append(f'    if show_labels')
            lines.append(
                f'        label.new(anchor-{age}+1, {top}, "{label}", '
                f'color=color.new(color.white, 100), textcolor=color.black, '
                f'style=label.style_none, size=size.tiny)'
            )
    return lines or _nothing("No Order Blocks detected")


# ── Breaker Blocks ────────────────────────────────────────────────────────────

def _pine_breaker_block(result: dict, future_bars: int) -> list[str]:
    """Same block pattern as OB — c_block_active / c_block_mit."""
    lines = []
    for z in result.get("breakers", []):
        age      = max(1, int(z["age_bars"]))
        top, bot = z["high"], z["low"]
        ztype    = z["type"]
        mit      = z.get("is_mitigated", False)
        tested   = " tested" if z.get("is_tested") else ""
        arrow    = "↑" if ztype == "bullish" else "↓"
        label    = f"BB{arrow}{tested}"
        if mit:
            lines.append(
                f'    box.new(anchor-{age}, {top}, anchor, {bot}, '
                f'bgcolor=c_block_mit, border_color=color.new(color.white, 100))'
            )
            lines.append(f'    if show_labels')
            lines.append(
                f'        label.new(anchor-{age}+1, {top}, "{label} mit", '
                f'color=color.new(color.white, 100), textcolor=color.black, '
                f'style=label.style_none, size=size.tiny)'
            )
        else:
            lines.append(
                f'    box.new(anchor-{age}, {top}, anchor+{future_bars}, {bot}, '
                f'bgcolor=c_block_active, border_color=color.new(color.white, 100))'
            )
            lines.append(f'    if show_labels')
            lines.append(
                f'        label.new(anchor-{age}+1, {top}, "{label}", '
                f'color=color.new(color.white, 100), textcolor=color.black, '
                f'style=label.style_none, size=size.tiny)'
            )
    return lines or _nothing("No Breaker Blocks detected")


# ── Rejection Blocks ──────────────────────────────────────────────────────────

def _pine_rejection_block(result: dict, future_bars: int) -> list[str]:
    """Same block pattern — c_block_active / c_block_mit."""
    lines = []
    for z in result.get("blocks", []):
        age      = max(1, int(z["age_bars"]))
        top, bot = z["high"], z["low"]
        ztype    = z["type"]
        mit      = z.get("is_mitigated", False)
        arrow    = "↑" if ztype == "bullish" else "↓"
        label    = f"RB{arrow}"
        if mit:
            lines.append(
                f'    box.new(anchor-{age}, {top}, anchor, {bot}, '
                f'bgcolor=c_block_mit, border_color=color.new(color.white, 100))'
            )
            lines.append(f'    if show_labels')
            lines.append(
                f'        label.new(anchor-{age}+1, {top}, "{label} mit", '
                f'color=color.new(color.white, 100), textcolor=color.black, '
                f'style=label.style_none, size=size.tiny)'
            )
        else:
            lines.append(
                f'    box.new(anchor-{age}, {top}, anchor+{future_bars}, {bot}, '
                f'bgcolor=c_block_active, border_color=color.new(color.white, 100))'
            )
            lines.append(f'    if show_labels')
            lines.append(
                f'        label.new(anchor-{age}+1, {top}, "{label}", '
                f'color=color.new(color.white, 100), textcolor=color.black, '
                f'style=label.style_none, size=size.tiny)'
            )
    return lines or _nothing("No Rejection Blocks detected")


# ── Mitigation Blocks ─────────────────────────────────────────────────────────

def _pine_mitigation_block(result: dict, future_bars: int) -> list[str]:
    """Same block pattern — c_block_active / c_block_mit."""
    lines = []
    for z in result.get("blocks", []):
        age      = max(1, int(z["age_bars"]))
        top, bot = z["high"], z["low"]
        ztype    = z["type"]
        mit      = z.get("is_mitigated", False)
        arrow    = "↑" if ztype == "bullish" else "↓"
        label    = f"MB{arrow}"
        if mit:
            lines.append(
                f'    box.new(anchor-{age}, {top}, anchor, {bot}, '
                f'bgcolor=c_block_mit, border_color=color.new(color.white, 100))'
            )
            lines.append(f'    if show_labels')
            lines.append(
                f'        label.new(anchor-{age}+1, {top}, "{label} mit", '
                f'color=color.new(color.white, 100), textcolor=color.black, '
                f'style=label.style_none, size=size.tiny)'
            )
        else:
            lines.append(
                f'    box.new(anchor-{age}, {top}, anchor+{future_bars}, {bot}, '
                f'bgcolor=c_block_active, border_color=color.new(color.white, 100))'
            )
            lines.append(f'    if show_labels')
            lines.append(
                f'        label.new(anchor-{age}+1, {top}, "{label}", '
                f'color=color.new(color.white, 100), textcolor=color.black, '
                f'style=label.style_none, size=size.tiny)'
            )
    return lines or _nothing("No Mitigation Blocks detected")


# ── Liquidity ─────────────────────────────────────────────────────────────────

def _pine_liquidity(result: dict, df: pd.DataFrame, future_bars: int) -> list[str]:
    """
    Unswept BSL/SSL: c_structure dashed line.
    Sweeps: c_structure solid line + ✕ marker at midpoint.
    Debug extra: touches count shown in label.
    """
    lines = []
    for pool in result.get("buyside_liquidity", []):
        age     = max(1, int(pool["age_bars"]))
        price   = pool["price"]
        touches = pool.get("touches", 0)
        lines.append(
            f'    line.new(anchor-{age}, {price}, anchor+{future_bars}, {price}, '
            f'color=c_structure, style=line.style_dashed, width=1)'
        )
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor-{age}+1, {price}, '
            f'"BSL {price} x{touches}", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.tiny)'
        )
    for pool in result.get("sellside_liquidity", []):
        age     = max(1, int(pool["age_bars"]))
        price   = pool["price"]
        touches = pool.get("touches", 0)
        lines.append(
            f'    line.new(anchor-{age}, {price}, anchor+{future_bars}, {price}, '
            f'color=c_structure, style=line.style_dashed, width=1)'
        )
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor-{age}+1, {price}, '
            f'"SSL {price} x{touches}", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.tiny)'
        )
    for sweep in result.get("recent_sweeps", []):
        try:
            ts = pd.Timestamp(sweep["sweep_ts"])
            if ts.tzinfo is None:
                ts = ts.tz_localize("UTC")
            age_sweep = max(1, _ts_to_age(df, sweep["sweep_ts"]))
        except Exception:
            continue
        age_level = age_sweep + 10      # approximate fractal age
        mid_age   = (age_level + age_sweep) // 2
        level     = sweep["swept_level"]
        side_tag  = "BSL" if sweep["side"] == "buyside" else "SSL"
        closed    = sweep.get("closed_back", False)
        # Solid line from fractal to sweep bar
        lines.append(
            f'    line.new(anchor-{age_level}, {level}, anchor-{age_sweep}, {level}, '
            f'color=c_structure, style=line.style_solid, width=1)'
        )
        # ✕ marker at midpoint
        lines.append(
            f'    label.new(anchor-{mid_age}, {level}, "✕", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.small)'
        )
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor-{age_level}+1, {level}, '
            f'"{side_tag} swept{"·cb" if closed else ""}", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.tiny)'
        )
    return lines or _nothing("No liquidity levels detected")


# ── BOS / cBOS ────────────────────────────────────────────────────────────────

def _pine_bos(result: dict, df: pd.DataFrame, future_bars: int, swing_lookback: int = 5) -> list[str]:
    """
    All BOS / cBOS events, drawn the same way as _pine_market_structure: the line
    runs from the ACTUAL broken swing to the break candle (no synthetic +8 left
    edge), so every line starts at the fractal it broke and ends at the candle
    whose close crossed the level. Labels use style_none (no vertical pointer).
    c_structure solid line: 2px=BOS, 1px=cBOS. Debug extra: break-candle body/ATR.
    """
    if result.get("status"):
        return _nothing(f"BOS: {result['status']}")

    from copilot.detectors.smc_lib import lib_swings, structure_events, true_range_atr

    shl    = lib_swings(df, swing_lookback)
    events = structure_events(df, shl)   # oldest-first, with swing_idx / break_idx
    if not events:
        return _nothing("No BOS / cBOS events")

    opens  = df["open"].values
    closes = df["close"].values
    atr    = true_range_atr(df)
    n      = len(df)

    lines: list[str] = []
    for i, ev in enumerate(events):
        age_swing = max(1, n - 1 - ev["swing_idx"])
        age_break = max(1, n - 1 - ev["break_idx"])
        level     = round(ev["level"], 2)
        width     = 2 if ev["type"] == "BOS" else 1
        color     = "c_structure" if ev["direction"] == "bullish" else "c_fvg_line"
        arrow     = "↑" if ev["direction"] == "bullish" else "↓"
        j         = ev["break_idx"]
        av        = float(atr[j]) if atr[j] > 0 else 1.0
        body_atr  = round(abs(closes[j] - opens[j]) / av, 2)

        # Line: broken swing → break candle, at the broken level.
        lines.append(
            f'    line.new(anchor-{age_swing}, {level}, anchor-{age_break}, {level}, '
            f'color={color}, style=line.style_solid, width={width})'
        )
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor-{age_break}, {level}, '
            f'"{ev["type"]}{arrow} #{i+1} | {body_atr:.2f}xATR", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.tiny)'
        )

    # Summary label
    latest = result.get("latest_bias", "none")
    count  = result.get("count", len(events))
    lc     = "c_fvg_line" if latest == "bearish" else ("c_structure" if latest == "bullish" else "c_block_active")
    lines.append(
        f'    label.new(anchor+1, close, '
        f'"BOS: {count} events | bias: {latest}", '
        f'color={lc}, textcolor=color.white, style=label.style_label_left, size=size.small)'
    )
    return lines


# ── Volume Profile ────────────────────────────────────────────────────────────

def _pine_volume_profile(result: dict, bars: int, future_bars: int) -> list[str]:
    """
    B&W style: c_vp_poc for POC (dashed line + bar), c_vp_hvn/lvn for nodes.
    VAH/VAL as grey (#888) dashed lines.
    """
    if result.get("status"):
        return _nothing(f"Volume profile: {result['status']}")
    lines = []
    poc = result.get("poc")
    vah = result.get("vah")
    val = result.get("val")
    loc = result.get("current_price_location", "")
    left = bars - 1

    if poc:
        lines += [
            f'    line.new(anchor-{left}, {poc}, anchor+{future_bars}, {poc}, '
            f'color=c_vp_poc, style=line.style_dashed, width=1)',
        ]
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor, {poc}, "POC {poc} | {loc}", '
            f'color=c_vp_poc, textcolor=color.white, '
            f'style=label.style_label_left, size=size.small)'
        )
    for lvl, lbl in [(vah, "VAH"), (val, "VAL")]:
        if lvl:
            lines.append(
                f'    line.new(anchor-{left}, {lvl}, anchor+{future_bars}, {lvl}, '
                f'color=color.new(#888888, 40), style=line.style_dashed, width=1)'
            )
            lines.append(f'    if show_labels')
            lines.append(
                f'        label.new(anchor, {lvl}, "{lbl} {lvl}", '
                f'color=color.new(#888888, 40), textcolor=color.white, '
                f'style=label.style_label_left, size=size.tiny)'
            )
    for node in result.get("hvn_nodes", [])[:15]:
        ph, pl = node["price_high"], node["price_low"]
        vpct   = node["volume_pct"]
        is_poc = (pl <= poc <= ph) if poc else False
        col    = "c_vp_poc" if is_poc else "c_vp_hvn"
        lines.append(
            f'    box.new(anchor-{left}, {ph}, anchor+{future_bars}, {pl}, '
            f'bgcolor={col}, border_color=color.new(color.white, 100))'
        )
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor+{future_bars}+1, {round((ph+pl)/2, 2)}, '
            f'"HVN {vpct:.1f}%", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.tiny)'
        )
    for node in result.get("lvn_nodes", [])[:15]:
        ph, pl = node["price_high"], node["price_low"]
        vpct   = node["volume_pct"]
        lines.append(
            f'    box.new(anchor-{left}, {ph}, anchor+{future_bars}, {pl}, '
            f'bgcolor=c_vp_lvn, border_color=color.new(color.white, 100))'
        )
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor+{future_bars}+1, {round((ph+pl)/2, 2)}, '
            f'"LVN {vpct:.1f}%", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.tiny)'
        )
    return lines or _nothing("Volume profile: no levels")


# ── Market Structure ──────────────────────────────────────────────────────────

def _pine_market_structure(
    result: dict, df: pd.DataFrame, future_bars: int, swing_lookback: int = 5
) -> list[str]:
    """
    Draws EXACTLY what the rewritten detector computes (P0-3):
    confirmed library swings + close-break structure events from
    smc.bos_choch. No re-derived state machine — if the chart disagrees
    with the detector output, that IS the bug being looked for.

    B&W style:
      Swing highs  — c_structure triangle-down markers
      Swing lows   — c_block_active triangle-up markers
      Event line   — swing → break bar at the broken level (2px BOS, 1px cBOS)
      Bullish event label — c_structure (black), bearish — c_fvg_line (red)
      Last SwH/SwL lines — dotted
    """
    if result.get("status"):
        return _nothing(f"Market structure: {result['status']}")

    from copilot.detectors.smc_lib import confirmed_swings, lib_swings, structure_events

    shl    = lib_swings(df, swing_lookback)
    swings = confirmed_swings(shl, df)
    events = structure_events(df, shl)
    n      = len(df)
    lines: list[str] = []

    # ── 1. Confirmed swing markers (boundary synthetics excluded) ────────────
    for s in swings:
        age   = max(1, n - 1 - s["idx"])
        price = round(s["price"], 2)
        if s["type"] == "high":
            lines.append(
                f'    label.new(anchor-{age}, {price}, "H {price}", '
                f'color=c_structure, textcolor=color.white, '
                f'style=label.style_triangledown, size=size.tiny)'
            )
        else:
            lines.append(
                f'    label.new(anchor-{age}, {price}, "L {price}", '
                f'color=c_block_active, textcolor=color.white, '
                f'style=label.style_triangleup, size=size.tiny)'
            )

    # ── 2. Structure events: line from the swing to the break bar ────────────
    # Verify manually: the line must END at a candle whose CLOSE crossed the
    # level. A wick touching it must not produce an event.
    for i, ev in enumerate(events):
        age_swing = max(1, n - 1 - ev["swing_idx"])
        age_break = max(1, n - 1 - ev["break_idx"])
        level     = round(ev["level"], 2)
        width     = 2 if ev["type"] == "BOS" else 1
        color     = "c_structure" if ev["direction"] == "bullish" else "c_fvg_line"
        style     = ("label.style_label_up" if ev["direction"] == "bullish"
                     else "label.style_label_down")
        arrow     = "↑" if ev["direction"] == "bullish" else "↓"
        lines.append(
            f'    line.new(anchor-{age_swing}, {level}, anchor-{age_break}, {level}, '
            f'color={color}, style=line.style_solid, width={width})'
        )
        lines.append(
            f'    label.new(anchor-{age_break}, {level}, '
            f'"{ev["type"]}{arrow} #{i+1} @{level}", '
            f'color={color}, textcolor=color.white, style={style}, size=size.tiny)'
        )

    # ── 3. Last SwH / SwL dotted extension lines ──────────────────────────────
    sh = result.get("last_swing_high") or {}
    sl = result.get("last_swing_low")  or {}
    if sh.get("price") and sh.get("ts"):
        sh_age = max(1, _ts_to_age(df, sh["ts"]))
        sh_p   = sh["price"]
        lines += [
            f'    line.new(anchor-{sh_age}, {sh_p}, anchor+{future_bars}, {sh_p}, '
            f'color=c_structure, style=line.style_dotted, width=1)',
        ]
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor, {sh_p}, "SwH {sh_p}", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.tiny)'
        )
    if sl.get("price") and sl.get("ts"):
        sl_age = max(1, _ts_to_age(df, sl["ts"]))
        sl_p   = sl["price"]
        lines += [
            f'    line.new(anchor-{sl_age}, {sl_p}, anchor+{future_bars}, {sl_p}, '
            f'color=c_block_active, style=line.style_dotted, width=1)',
        ]
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor, {sl_p}, "SwL {sl_p}", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.tiny)'
        )

    # ── 4. Summary label ─────────────────────────────────────────────────────
    state         = result.get("state", "unknown")
    bars_in_state = result.get("bars_in_state", 0)
    current_price = result.get("current_price", 0)
    atr           = result.get("atr_14", 0)
    last_bos_type = result.get("last_bos_type") or "—"
    state_col     = (
        "c_structure"  if state == "bullish" else
        "c_fvg_line"   if state == "bearish" else
        "c_block_active"
    )
    lines.append(
        f'    label.new(anchor+1, {current_price}, '
        f'"MS: {state} ({last_bos_type}) | {bars_in_state} bars | ATR:{atr}", '
        f'color={state_col}, textcolor=color.white, '
        f'style=label.style_label_left, size=size.small)'
    )
    return lines or _nothing("No swing points detected")


# ── Fractals ──────────────────────────────────────────────────────────────────

def _pine_fractals(result: dict, future_bars: int) -> list[str]:
    """
    Swing highs: c_structure triangle-down (fresh) / c_block_active (swept).
    Swing lows:  c_block_active triangle-up (fresh) / c_block_mit (swept).
    Price shown in label.
    """
    lines = []
    for f in result.get("fractals", []):
        age   = max(1, int(f["age_bars"]))
        price = f["price"]
        ftype = f["type"]
        swept = f["is_swept"]
        if ftype == "swing_high":
            color = "c_block_active" if swept else "c_structure"
            style = "label.style_triangledown"
            txt   = f"H {price}"
        else:
            color = "c_block_mit" if swept else "c_block_active"
            style = "label.style_triangleup"
            txt   = f"L {price}"
        lines.append(
            f'    label.new(anchor-{age}, {price}, "{txt}", '
            f'color={color}, textcolor=color.white, style={style}, size=size.tiny)'
        )
    return lines or _nothing("No fractals detected")


# ── Fib Zones ─────────────────────────────────────────────────────────────────

def _pine_fib_zones(result: dict, bars: int, future_bars: int) -> list[str]:
    """
    Premium / Discount: c_block_active boxes.
    OTE (61.8–78.6%): c_fvg_fill (hot zone).
    EQ 50% line: c_structure dashed.
    Key fib levels: c_block_active dotted.
    """
    if result.get("status"):
        return _nothing(f"Fib zones: {result['status']}")
    lines = []
    left      = bars - 1
    pz        = result.get("premium_zone", {})
    dz        = result.get("discount_zone", {})
    ote       = result.get("ote", {})
    eq        = result.get("equilibrium")
    key       = result.get("key_levels", {})
    loc       = result.get("current_price_location", "")
    in_ote    = result.get("in_ote", False)
    cur       = result.get("current_price", 0)
    fib_ratio = result.get("current_fib_ratio", 0)

    if pz.get("upper") and pz.get("lower"):
        lines.append(
            f'    box.new(anchor-{left}, {pz["upper"]}, anchor+{future_bars}, {pz["lower"]}, '
            f'bgcolor=c_block_active, border_color=color.new(color.white, 100))'
        )
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor-{left}+1, {pz["upper"]}, "Premium", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.small)'
        )
    if dz.get("upper") and dz.get("lower"):
        lines.append(
            f'    box.new(anchor-{left}, {dz["upper"]}, anchor+{future_bars}, {dz["lower"]}, '
            f'bgcolor=c_block_active, border_color=color.new(color.white, 100))'
        )
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor-{left}+1, {dz["lower"]}, "Discount", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.small)'
        )
    if ote.get("upper") and ote.get("lower"):
        lines.append(
            f'    box.new(anchor-{left}, {ote["upper"]}, anchor+{future_bars}, {ote["lower"]}, '
            f'bgcolor=c_fvg_fill, border_color=c_fvg_line)'
        )
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor-{left}+1, {ote["upper"]}, "OTE 61.8-78.6%", '
            f'color=c_fvg_line, textcolor=color.white, '
            f'style=label.style_none, size=size.small)'
        )
    if eq:
        lines += [
            f'    line.new(anchor-{left}, {eq}, anchor+{future_bars}, {eq}, '
            f'color=c_structure, style=line.style_dashed, width=1)',
        ]
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor, {eq}, "EQ 50%", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.tiny)'
        )
    for fib_key in ("0.0", "0.236", "0.382", "0.618", "0.786", "1.0"):
        price = key.get(fib_key)
        if price:
            lines += [
                f'    line.new(anchor-{left}, {price}, anchor+{future_bars}, {price}, '
                f'color=c_block_active, style=line.style_dotted, width=1)',
            ]
            lines.append(f'    if show_labels')
            lines.append(
                f'        label.new(anchor-{left}, {price}, "{fib_key}", '
                f'color=color.new(color.white, 100), textcolor=color.black, '
                f'style=label.style_none, size=size.tiny)'
            )
    ote_tag = " IN OTE!" if in_ote else ""
    lines.append(
        f'    label.new(anchor, {cur}, "Loc: {loc}{ote_tag} | ratio: {fib_ratio:.3f}", '
        f'color=c_structure, textcolor=color.white, '
        f'style=label.style_label_left, size=size.small)'
    )
    return lines


# ── Compression ───────────────────────────────────────────────────────────────

def _pine_compression(result: dict, df: pd.DataFrame, future_bars: int) -> list[str]:
    """
    Active: c_fvg_fill (hot — price is coiling).
    Ended:  c_block_active (neutral).
    """
    if result.get("status"):
        return _nothing(f"Compression: {result['status']}")
    lines = []
    for c in result.get("compressions", []):
        age_end   = max(1, c["bars_since_end"])
        age_start = age_end + c["bars"] - 1
        ph, pl    = _compression_bounds(df, c["start_ts"], c["end_ts"])
        if ph is None:
            continue
        is_active = c["is_active"]
        bg        = "c_fvg_fill"     if is_active else "c_block_active"
        bc        = "c_fvg_line"     if is_active else "color.new(color.white, 100)"
        txt = (f"COMP {'ACTIVE' if is_active else 'ended'} "
               f"{c['bars']}b sq:{c['squeeze_ratio']}x "
               f"tAtr:{c['tightest_range_atr']}")
        lines.append(
            f'    box.new(anchor-{age_start}, {ph}, anchor-{age_end}, {pl}, '
            f'bgcolor={bg}, border_color={bc})'
        )
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor-{age_start}+1, {ph}, "{txt}", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.tiny)'
        )
    return lines or _nothing("No compressions detected")


def _compression_bounds(df: pd.DataFrame, start_ts: str, end_ts: str) -> tuple[float | None, float | None]:
    """Get the actual high/low of the price range during a compression window."""
    try:
        s = pd.Timestamp(start_ts, tz="UTC") if "+" not in start_ts and "Z" not in start_ts \
            else pd.Timestamp(start_ts)
        e = pd.Timestamp(end_ts,   tz="UTC") if "+" not in end_ts   and "Z" not in end_ts \
            else pd.Timestamp(end_ts)
        if s.tzinfo is None:
            s = s.tz_localize("UTC")
        if e.tzinfo is None:
            e = e.tz_localize("UTC")
        mask = (df.index >= s) & (df.index <= e)
        if not mask.any():
            return None, None
        return float(df.loc[mask, "high"].max()), float(df.loc[mask, "low"].min())
    except Exception:
        return None, None


# ── Sponsored Candle ──────────────────────────────────────────────────────────

def _pine_sponsored_candle(result: dict, future_bars: int) -> list[str]:
    """
    High-quality OB — same block style as OB: c_block_active / c_block_mit.
    Sweep side shown in label.
    """
    if result.get("status"):
        return _nothing(f"Sponsored candle: {result['status']}")
    lines = []
    for z in result.get("candles", []):
        age      = max(1, int(z["age_bars"]))
        top, bot = z["high"], z["low"]
        ztype    = z["ob_type"]
        mit      = z.get("is_mitigated", False)
        sw_side  = z.get("sweep_side", "?")[:3]
        arrow    = "↑" if ztype == "bullish" else "↓"
        label    = f"SpC{arrow} sw:{sw_side}"
        if mit:
            lines.append(
                f'    box.new(anchor-{age}, {top}, anchor, {bot}, '
                f'bgcolor=c_block_mit, border_color=color.new(color.white, 100))'
            )
            lines.append(f'    if show_labels')
            lines.append(
                f'        label.new(anchor-{age}+1, {top}, "{label} mit", '
                f'color=color.new(color.white, 100), textcolor=color.black, '
                f'style=label.style_none, size=size.tiny)'
            )
        else:
            lines.append(
                f'    box.new(anchor-{age}, {top}, anchor+{future_bars}, {bot}, '
                f'bgcolor=c_block_active, border_color=color.new(color.white, 100))'
            )
            lines.append(f'    if show_labels')
            lines.append(
                f'        label.new(anchor-{age}+1, {top}, "{label}", '
                f'color=color.new(color.white, 100), textcolor=color.black, '
                f'style=label.style_none, size=size.tiny)'
            )
    return lines or _nothing("No sponsored candles detected")


# ── Absorption at POI ─────────────────────────────────────────────────────────

def _pine_absorption_poi(result: dict, future_bars: int) -> list[str]:
    """
    Absorbed: c_fvg_fill with c_fvg_line border (hot = trade setup).
    Not absorbed: c_block_active (neutral).
    Debug metrics shown in side label.
    """
    poi_zone = result.get("poi_zone")
    poi_type = result.get("poi_type", "none")
    reversal = result.get("reversal_direction", "none")
    absorbed = result.get("absorption_detected", False)
    poi_hit  = result.get("poi_hit", False)
    if not poi_zone or poi_type == "none":
        return _nothing(f"No POI absorption — poi_type:{poi_type} hit:{poi_hit}")
    ph = poi_zone["high"]
    pl = poi_zone["low"]
    bg = "c_fvg_fill"   if absorbed else "c_block_active"
    bc = "c_fvg_line"   if absorbed else "color.new(color.white, 100)"
    txt = f"Abs:{'YES' if absorbed else 'no'} | {poi_type} | rev:{reversal}"
    lines = [
        f'    box.new(anchor-5, {ph}, anchor+{future_bars}, {pl}, '
        f'bgcolor={bg}, border_color={bc})',
    ]
    lines.append(f'    if show_labels')
    lines.append(
        f'        label.new(anchor+{future_bars}+1, {round((ph+pl)/2, 2)}, "{txt}", '
        f'color=color.new(color.white, 100), textcolor=color.black, '
        f'style=label.style_none, size=size.small)'
    )
    detail = result.get("absorption_detail", {})
    if detail:
        vr = detail.get("vol_ratio", 0)
        cp = detail.get("close_position", 0)
        ar = detail.get("range_atr_ratio", 0)
        lines.append(f'    if show_labels')
        lines.append(
            f'        label.new(anchor+{future_bars}+1, {pl}, '
            f'"vol:{vr:.2f} cls:{cp:.2f} atr:{ar:.2f}", '
            f'color=color.new(color.white, 100), textcolor=color.black, '
            f'style=label.style_none, size=size.tiny)'
        )
    return lines


# ── Cumulative Delta ──────────────────────────────────────────────────────────

def _pine_cumulative_delta(result: dict, df: pd.DataFrame, future_bars: int) -> list[str]:
    """
    Session delta trend label: c_fvg_line if negative (warning), c_structure if positive.
    CD divergence markers: c_fvg_line triangles (divergence = alert regardless of direction).
    """
    if result.get("status"):
        return _nothing(f"Cumulative delta: {result['status']}")
    lines = []
    trend = result.get("delta_trend", "neutral")
    delta = result.get("session_delta", 0)
    # Negative delta (selling pressure) = c_fvg_line, positive = c_structure
    tc = "c_fvg_line" if trend == "negative" else ("c_structure" if trend == "positive" else "c_block_active")
    lines.append(
        f'    label.new(anchor+1, close, "CD session:{delta:.1f} trend:{trend}", '
        f'color={tc}, textcolor=color.white, style=label.style_label_left, size=size.small)'
    )
    for div in result.get("divergences", []):
        dtype  = div["type"]
        bar_ts = div.get("bar_ts")
        price  = div.get("price_high") or div.get("price_low") or 0
        if not (price and bar_ts):
            continue
        age   = _ts_to_age(df, bar_ts)
        # Both divergence types = c_fvg_line (red = disagreement between price and delta)
        # P0-5 semantics to verify: the marker must sit on the window's price
        # extreme (confirmed, never the live bar), with CD already declining
        # (bearish) / rising (bullish) into it.
        style = "label.style_triangledown" if dtype == "bearish" else "label.style_triangleup"
        lines.append(
            f'    label.new(anchor-{age}, {price}, "CD div {dtype}", '
            f'color=c_fvg_line, textcolor=color.white, style={style}, size=size.small)'
        )

    # P0-5 sweep confirmation — pool-anchored, close-back. Verify: the marked
    # bar must WICK beyond a liquidity pool and close back inside; a bar that
    # closed through the level must never carry this marker.
    sweep = result.get("sweep_confirmation")
    if sweep and sweep.get("last_sweep_ts"):
        age   = _ts_to_age(df, sweep["last_sweep_ts"])
        side  = sweep.get("sweep_side", "?")
        manip = sweep.get("confirmed_manipulation", False)
        cd_at = sweep.get("cd_at_sweep", 0)
        col   = "c_fvg_line" if manip else "c_block_active"
        lines.append(
            f'    label.new(anchor-{age}, high[{age}], '
            f'"SWEEP {side} | delta:{cd_at:+.1f} | manip:{"YES" if manip else "no"}", '
            f'color={col}, textcolor=color.white, '
            f'style=label.style_label_down, size=size.small)'
        )

    if len(lines) == 1:
        lines.append(_nothing("No CD divergences / sweeps")[0])
    return lines


# ── CD Divergence at Structure ────────────────────────────────────────────────

def _pine_cd_divergence(result: dict, df: pd.DataFrame, future_bars: int) -> list[str]:
    """
    Detected: c_fvg_line for bearish div (red = alert), c_structure for bullish.
    Sweep marker: c_fvg_line label_up.
    """
    if result.get("reason"):
        return _nothing(f"CDdiv: {result['reason']}")
    detected    = result.get("divergence_detected", False)
    dtype       = result.get("type", "none")
    at_struct   = result.get("at_structure", False)
    level       = result.get("structure_level")
    struct_type = result.get("structure_type", "")
    strength    = result.get("signal_strength", "none")
    sweep_prec  = result.get("sweep_preceded", False)
    sweep_ts    = result.get("sweep_ts")
    if not (detected and level):
        return _nothing(
            f"No CD div | type:{dtype} at_struct:{at_struct} strength:{strength}"
        )
    # Bearish divergence = c_fvg_line (red), bullish = c_structure (black)
    lc  = "c_fvg_line" if dtype == "bearish" else "c_structure"
    txt = f"CD {dtype} @ {struct_type} | {strength}{'  swept' if sweep_prec else ''}"
    lines = [
        f'    line.new(0, {level}, anchor+{future_bars}, {level}, '
        f'color={lc}, style=line.style_dashed, width=2)',
    ]
    lines.append(f'    if show_labels')
    lines.append(
        f'        label.new(anchor, {level}, "{txt}", '
        f'color={lc}, textcolor=color.white, '
        f'style=label.style_label_left, size=size.small)'
    )
    if sweep_prec and sweep_ts:
        age = _ts_to_age(df, sweep_ts)
        lines.append(
            f'    label.new(anchor-{age}, {level}, "✕ SWEEP", '
            f'color=c_fvg_line, textcolor=color.white, '
            f'style=label.style_label_up, size=size.tiny)'
        )
    return lines


# ── Killzone ──────────────────────────────────────────────────────────────────

def _pine_killzone(result: dict) -> list[str]:
    """
    Session state table (top-right).
    Active killzone / OTT: c_fvg_line (red highlight).
    Inactive / neutral: c_block_active.
    Friday: c_structure (black = caution).
    """
    kz      = result.get("active_killzone") or "none"
    next_kz = result.get("next_killzone") or "—"
    t_str   = result.get("kyiv_time", "")
    weekday = result.get("weekday", "")
    ott     = result.get("in_ott_window", False)
    is_fri  = result.get("is_friday", False)
    kz_c    = "c_fvg_line"     if kz != "none" else "c_block_active"
    ott_c   = "c_fvg_line"     if ott          else "c_block_active"
    fri_c   = "c_structure"    if is_fri       else "c_block_active"
    return [
        f'    var _kzt = table.new(position.top_right, 2, 5, '
        f'bgcolor=color.new(color.white, 10), frame_color=c_block_active, frame_width=1)',
        f'    table.cell(_kzt, 0, 0, "Killzone",  text_color=c_block_active, text_size=size.small)',
        f'    table.cell(_kzt, 1, 0, "{kz}",       text_color={kz_c}, text_size=size.small)',
        f'    table.cell(_kzt, 0, 1, "Kyiv time",  text_color=c_block_active, text_size=size.small)',
        f'    table.cell(_kzt, 1, 1, "{t_str} {weekday}", text_color=c_structure, text_size=size.small)',
        f'    table.cell(_kzt, 0, 2, "OTT window", text_color=c_block_active, text_size=size.small)',
        f'    table.cell(_kzt, 1, 2, "{"YES" if ott else "no"}", text_color={ott_c}, text_size=size.small)',
        f'    table.cell(_kzt, 0, 3, "Next KZ",    text_color=c_block_active, text_size=size.small)',
        f'    table.cell(_kzt, 1, 3, "{next_kz}",  text_color=c_structure, text_size=size.small)',
        f'    table.cell(_kzt, 0, 4, "Friday",     text_color=c_block_active, text_size=size.small)',
        f'    table.cell(_kzt, 1, 4, "{"YES" if is_fri else "no"}", text_color={fri_c}, text_size=size.small)',
    ]


# ── Multi-TF Alignment ────────────────────────────────────────────────────────

def _pine_multi_tf(result: dict, htf: str, ltf: str) -> list[str]:
    """
    MTF alignment table (top-left).
    Aligned / bullish bias = c_structure (black = clear/positive).
    Not aligned / bearish = c_fvg_line (red = conflict/alert).
    desync = c_fvg_line.
    """
    aligned = result.get("aligned", False)
    bias    = result.get("htf_bias", "unknown")
    role    = result.get("ltf_role", "unknown")
    sync    = result.get("sync_quality", "unknown")
    al_c    = "c_structure"   if aligned             else "c_fvg_line"
    bias_c  = "c_structure"   if bias == "bullish"   else ("c_fvg_line" if bias == "bearish" else "c_block_active")
    sync_c  = {"strong": "c_structure", "weak": "c_block_active", "desync": "c_fvg_line"}.get(sync, "c_block_active")
    return [
        f'    var _mtft = table.new(position.top_left, 2, 4, '
        f'bgcolor=color.new(color.white, 10), frame_color=c_block_active, frame_width=1)',
        f'    table.cell(_mtft, 0, 0, "MTF Align ({htf}/{ltf})", text_color=c_block_active, text_size=size.small)',
        f'    table.cell(_mtft, 1, 0, "{"YES" if aligned else "NO"}", text_color={al_c}, text_size=size.small)',
        f'    table.cell(_mtft, 0, 1, "HTF bias ({htf})",          text_color=c_block_active, text_size=size.small)',
        f'    table.cell(_mtft, 1, 1, "{bias}",                    text_color={bias_c}, text_size=size.small)',
        f'    table.cell(_mtft, 0, 2, "LTF role ({ltf})",          text_color=c_block_active, text_size=size.small)',
        f'    table.cell(_mtft, 1, 2, "{role}",                    text_color=c_structure, text_size=size.small)',
        f'    table.cell(_mtft, 0, 3, "Sync quality",              text_color=c_block_active, text_size=size.small)',
        f'    table.cell(_mtft, 1, 3, "{sync}",                    text_color={sync_c}, text_size=size.small)',
    ]




# ── Uniform dispatch ──────────────────────────────────────────────────────────
# The emitter bodies above take heterogeneous arguments (some need the
# DataFrame, some the bar count, some the swing lookback). EmitContext carries
# every one of them so callers hand over a single object, and EMITTERS adapts
# each signature to the common (result, ctx) -> list[str] shape.

@dataclass(frozen=True)
class EmitContext:
    """Everything an emitter may need beyond the detector result itself."""

    df: pd.DataFrame
    bars: int
    future_bars: int = 50
    swing_lookback: int = 5
    htf: str = "4h"
    ltf: str = "1h"


EMITTERS: dict[str, Callable[[dict, EmitContext], list[str]]] = {
    "detect_fvg":                       lambda r, c: _pine_fvg(r, c.future_bars),
    "detect_ifvg":                      lambda r, c: _pine_ifvg(r, c.future_bars),
    "detect_order_block":               lambda r, c: _pine_order_block(r, c.future_bars),
    "detect_breaker_block":             lambda r, c: _pine_breaker_block(r, c.future_bars),
    "detect_rejection_block":           lambda r, c: _pine_rejection_block(r, c.future_bars),
    "detect_mitigation_block":          lambda r, c: _pine_mitigation_block(r, c.future_bars),
    "detect_sponsored_candle":          lambda r, c: _pine_sponsored_candle(r, c.future_bars),
    "detect_fractals":                  lambda r, c: _pine_fractals(r, c.future_bars),
    "detect_liquidity":                 lambda r, c: _pine_liquidity(r, c.df, c.future_bars),
    "detect_bos":                       lambda r, c: _pine_bos(r, c.df, c.future_bars, c.swing_lookback),
    "detect_market_structure":          lambda r, c: _pine_market_structure(r, c.df, c.future_bars, c.swing_lookback),
    "detect_volume_profile":            lambda r, c: _pine_volume_profile(r, c.bars, c.future_bars),
    "detect_fib_zones":                 lambda r, c: _pine_fib_zones(r, c.bars, c.future_bars),
    "detect_compression":               lambda r, c: _pine_compression(r, c.df, c.future_bars),
    "check_absorption_at_poi":          lambda r, c: _pine_absorption_poi(r, c.future_bars),
    "detect_cumulative_delta":          lambda r, c: _pine_cumulative_delta(r, c.df, c.future_bars),
    "check_cd_divergence_at_structure": lambda r, c: _pine_cd_divergence(r, c.df, c.future_bars),
    "current_killzone":                 lambda r, c: _pine_killzone(r),
    "check_multi_tf_alignment":         lambda r, c: _pine_multi_tf(r, c.htf, c.ltf),
}


def emit(detector: str, result: dict, ctx: EmitContext) -> list[str]:
    """Pine body lines for *detector*. Raises KeyError for an unknown name."""
    return EMITTERS[detector](result, ctx)


# Public aliases — the debug CLI and the overlay builder both need these.
now_str = _now_str
file_header = _header
assemble = _assemble
nothing = _nothing
